### PR TITLE
A04-spelling bee extension

### PR DESCRIPTION
**Pull request by Harshini-Jesi**

### CODE REVIEW

**Comment by Harshini-Jesi** [comment]
words.txt file added.

**Review by MetaNaveen — APPROVED** [review]

**Review by MetaNaveen — APPROVED** [review]
**Final Notes:**

- small case letters could be handled as well.
- Add comments wherever possible.

**Comment by MetaNaveen** [comment]
Working fine.

**Comment by Harshini-Jesi** [comment]
Minor correction done.

**Pull request closed without merging**
